import {
  ResourcesPageShell, GuideLayout, GuideHero, GuideSection, GuidePara, GuideCallout, GuideList, EduDisclaimer,
} from "../../../components/resources/ResourceComponents";

const GF = { fontFamily: "'Geist', sans-serif" };
const GM = { fontFamily: "'Geist Mono', monospace" };

export function AuthGuide() {
  return (
    <ResourcesPageShell>
      <GuideLayout
        hero={
          <GuideHero
            eyebrow="Authentication Guide"
            title="Signer authentication — how it works and how to choose."
            sub="Authentication helps increase confidence that the intended participant is acting. This guide explains access methods, authentication types, and how to choose the right approach."
          />
        }
      >
        <GuideSection id="access-vs-auth" title="Access versus authentication">
          <GuidePara>
            Access and authentication are related but distinct. Access refers to how a participant opens the signing document. Authentication refers to additional steps the participant completes to confirm their identity before they can sign.
          </GuidePara>
          <GuidePara>
            In LAGDA, a participant receives a unique secure invitation by email. Opening that link provides access. If the sender has configured an additional authentication step — such as email OTP or SMS OTP — the participant must also complete that step before they can view and sign the document.
          </GuidePara>
        </GuideSection>

        <GuideSection id="methods" title="Authentication methods">
          {[
            {
              name: "Secure invitation link",
              desc: "A unique one-time link delivered to the participant's email address. The link provides access to the document. Security depends on the participant being the person who controls that email address.",
              caution: "Forwarding the invitation link may allow someone other than the intended participant to access the document. This method has lower assurance than additional authentication steps.",
              plans: "All plans",
            },
            {
              name: "Verified email access",
              desc: "The participant confirms access to the registered email address before viewing the document.",
              plans: "All plans",
            },
            {
              name: "Email OTP",
              desc: "A one-time passcode is sent to the participant's email address. The participant must enter this code before proceeding to sign.",
              caution: "Where the invitation link and the OTP are delivered to the same email channel, this does not constitute a true second authentication factor — both rely on the same email address.",
              plans: "All plans",
            },
            {
              name: "SMS OTP",
              desc: "A one-time passcode is delivered via SMS to a confirmed mobile number. This adds a separate channel from the email invitation, increasing assurance.",
              plans: "Business and Enterprise",
            },
            {
              name: "Authenticator app (TOTP)",
              desc: "A time-based one-time passcode generated by the participant's authenticator app. Requires the participant to have previously enrolled a device.",
              plans: "Business and Enterprise",
            },
            {
              name: "Account authentication",
              desc: "The participant authenticates through their existing LAGDA account. Useful for regular collaborators or internal signers who already have accounts.",
              plans: "All plans",
            },
            {
              name: "Identity-document verification",
              desc: "A planned future capability where the participant's government-issued ID is verified as part of the signing process.",
              caution: "This is a planned future capability — not yet available.",
              plans: "Future capability",
            },
            {
              name: "Enterprise SSO / identity provider",
              desc: "Participants authenticate through your organization's enterprise identity provider (e.g., Microsoft Entra ID / Azure AD, Okta). Requires an Enterprise arrangement.",
              plans: "Enterprise",
            },
          ].map(({ name, desc, caution, plans }) => (
            <div key={name} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10, padding: "14px 18px", marginBottom: 10 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap", marginBottom: 6 }}>
                <p style={{ color: "white", ...GF, fontSize: 14, fontWeight: 700, margin: 0 }}>{name}</p>
                <span style={{ color: "#38bdf8", ...GM, fontSize: 9, fontWeight: 700, flexShrink: 0 }}>{plans.toUpperCase()}</span>
              </div>
              <p style={{ color: "#64748b", ...GF, fontSize: 13, margin: 0, lineHeight: 1.5 }}>{desc}</p>
              {caution && <p style={{ color: "#C9960C", ...GM, fontSize: 10, marginTop: 8, borderTop: "1px solid rgba(255,255,255,0.05)", paddingTop: 8 }}>⚠ {caution}</p>}
            </div>
          ))}
        </GuideSection>

        <GuideSection id="choosing" title="Choosing an authentication method">
          <GuidePara>
            No single method is right for every transaction. Consider these factors:
          </GuidePara>
          <GuideList items={[
            "Transaction risk and value: Higher-risk transactions generally benefit from stronger authentication",
            "Participant relationship: Known internal collaborators may need lighter friction; external parties or strangers may warrant more",
            "Available channels: SMS OTP requires a confirmed mobile number; authenticator app requires prior enrolment",
            "Legal requirements: Some document types or jurisdictions may specify minimum authentication standards",
            "User experience: More friction reduces signing drop-off risk but may also slow down completion",
            "Privacy: Some methods capture more personal information than others",
          ]} />
        </GuideSection>

        <GuideSection id="signature-adoption" title="Signature adoption and intent">
          <GuidePara>
            After completing any required authentication, participants review the document and adopt their signature. LAGDA records the moment of adoption with a timestamp and available device context.
          </GuidePara>
          <GuidePara>
            Signature adoption in LAGDA is designed to reflect the participant's intent to sign. The exact legal effect depends on the document, transaction, and applicable law — LAGDA does not determine legal sufficiency for a specific use.
          </GuidePara>
        </GuideSection>

        <GuideSection id="evidence" title="Authentication evidence">
          <GuidePara>
            LAGDA records authentication events in the audit trail. This typically includes:
          </GuidePara>
          <GuideList items={[
            "Invitation delivery timestamp",
            "Link opened timestamp",
            "Authentication method used",
            "Authentication completed timestamp",
            "Approximate device and browser context",
            "Signature adopted timestamp",
          ]} />
          <GuidePara>
            Authentication evidence is available in the completion report and audit trail associated with each transaction.
          </GuidePara>
        </GuideSection>

        <GuideSection id="caution" title="What authentication does not guarantee">
          <GuideCallout
            label="IMPORTANT NOTE"
            text="Authentication helps increase confidence that the intended participant is acting, but it does not independently determine legal identity or legal sufficiency in every transaction. Users remain responsible for determining the authentication requirements that apply to each document and transaction."
            color="#C9960C"
          />
        </GuideSection>

        <EduDisclaimer />
      </GuideLayout>
    </ResourcesPageShell>
  );
}
