// Product Capability Registry — C35
// Single canonical source of truth for all LAGDA product capabilities.
// Every navigation item, search provider, command, dashboard widget, and
// route guard resolves against this registry.
//
// Resolver:     src/app/config/capability-resolver.ts
// Models:       src/app/models/product-capability.ts
// Profile:      src/app/config/launch-profiles.ts

import type { ProductCapability, ProductCapabilityId } from "../models/product-capability";
import { capabilityId } from "../models/product-capability";

// ── Registry ──────────────────────────────────────────────────────────────────

const REGISTRY: ProductCapability[] = [

  // ── PUBLIC PORTAL ─────────────────────────────────────────────────────────
  {
    id:                       capabilityId("public-information-portal"),
    label:                    "Public Information Portal",
    description:              "LAGDA.io public website — home, product, pricing, resources, legal, eNotary future",
    group:                    "Public",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "not-defined",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["home","esignature","features","security","solutions","pricing","resources","help","contact","book-a-demo","legal"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/",
    indexable:                true,
    sitemapInclude:           true,
    backendDependencies:      [],
    dependencies:             [],
  },

  // ── AUTHENTICATION ────────────────────────────────────────────────────────
  {
    id:                       capabilityId("authentication"),
    label:                    "Authentication",
    description:              "Sign in, sign up, account recovery, MFA, invitation acceptance",
    group:                    "Account",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["sign-in","create-account","verify-email","forgot-password","reset-password","mfa-challenge","mfa-setup","recovery-codes","accept-invitation","account-locked","link-error"],
    unavailableReason:        "Authentication requires backend session management.",
    previewNotice:            "",
    safeFallbackRoute:        "/sign-in",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Auth service","Session management","Email OTP"],
    dependencies:             [],
  },

  // ── ONBOARDING ────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("onboarding"),
    label:                    "Onboarding",
    description:              "Post-signup onboarding flow — profile, use case, workspace, security, notifications",
    group:                    "Account",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["onboarding"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["User service","Workspace service"],
    dependencies:             [capabilityId("authentication")],
  },

  // ── DASHBOARD ─────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("dashboard"),
    label:                    "Dashboard",
    description:              "Authenticated sender dashboard — status, quick actions, recent documents",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_dashboard"],
    planRequirements:         [],
    featureRequirements:      ["dashboardEnabled"],
    routeIds:                 ["app-dashboard"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Document transaction service","Notification service"],
    dependencies:             [],
  },

  // ── DOCUMENTS ─────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("documents"),
    label:                    "Documents",
    description:              "Sender-side document transaction workspace",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-documents","app-documents-detail"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Document transaction service","File storage"],
    dependencies:             [],
  },

  // ── PREPARE DOCUMENT ──────────────────────────────────────────────────────
  {
    id:                       capabilityId("prepare-document"),
    label:                    "Prepare Document",
    description:              "Guided document preparation — upload, recipients, routing, fields, review",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["prepare_documents"],
    planRequirements:         [],
    featureRequirements:      ["prepareFlowEnabled"],
    routeIds:                 ["app-prepare"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Document transaction service","File storage","Participant service"],
    dependencies:             [capabilityId("documents")],
  },

  // ── SIGNING WORKFLOW (C37) ────────────────────────────────────────────────
  // Stage-based recipient routing for ONE document. This is NOT Workflow Automation.
  // Launch core, enabled by default, and completely independent of `automationEnabled`.
  {
    id:                       capabilityId("signing-workflow"),
    label:                    "Signing Workflow",
    description:              "Stage-based signing and approval routing for a document — stages, participant assignments, required actions, and individual eSignature requirements",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "contract-defined",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-document-workflow","app-document-workflow-create","app-document-workflow-review","app-document-workflow-stage"],
    unavailableReason:        "The signing workflow is not available for this document.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Signing workflow service","Routing state machine","Participant eligibility service","Field assignment validation","Notification event publication"],
    dependencies:             [capabilityId("documents")],
  },

  // ── WORKFLOW ──────────────────────────────────────────────────────────────
  // Reusable workflow TEMPLATES and the RUNS started from them. Distinct from
  // both neighbours and importing neither: `signing-workflow` routes ONE
  // document from its own detail page, and `workflow-automation` is a rules
  // engine. This is the layer that lets one design be started many times.
  {
    id:                       capabilityId("workflow"),
    label:                    "Workflow",
    description:              "Reusable multi-stage workflows — design a process once, start it as many times as needed, and track each run's stages, participants, progress and audit trail separately",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "contract-defined",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_workflow"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-workflow","app-workflow-templates","app-workflow-runs","app-workflow-completed","app-workflow-builder"],
    unavailableReason:        "Workflow is not available for your account.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Workflow template service","Workflow run state machine","Stage transition rules","Participant assignment service","Workflow notification events","Workflow audit trail"],
    dependencies:             [capabilityId("documents")],
  },

  // ── FIELD PLACEMENT ───────────────────────────────────────────────────────
  {
    id:                       capabilityId("field-placement"),
    label:                    "Field Placement",
    description:              "Sender-side field placement editor for signature, initials, text, and other fields",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   ["prepare_documents"],
    planRequirements:         [],
    featureRequirements:      ["prepareFlowEnabled"],
    routeIds:                 ["app-prepare-fields"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/prepare",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Field definition service"],
    dependencies:             [capabilityId("prepare-document")],
  },

  // ── RECIPIENT SIGNING ─────────────────────────────────────────────────────
  {
    id:                       capabilityId("recipient-signing"),
    label:                    "Recipient Signing",
    description:              "Recipient review, authentication, consent, signing, and completion flow",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["sign"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Recipient token service","Auth service","Signature service","Transaction state machine"],
    dependencies:             [],
  },

  // ── TEMPLATES ─────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("templates"),
    label:                    "Templates",
    description:              "Reusable document templates with roles and field definitions",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["manage_templates"],
    planRequirements:         [],
    featureRequirements:      ["templatesEnabled"],
    routeIds:                 ["app-templates"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Template service","Field definition service"],
    dependencies:             [],
  },

  // ── CONTACTS ──────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("contacts"),
    label:                    "Contacts",
    description:              "Signing participants and contact directory",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["manage_contacts"],
    planRequirements:         [],
    featureRequirements:      ["contactsEnabled"],
    routeIds:                 ["app-contacts"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Contact service"],
    dependencies:             [],
  },

  // ── VERIFICATION ──────────────────────────────────────────────────────────
  {
    id:                       capabilityId("verification"),
    label:                    "Document Verification",
    description:              "Verify document authenticity by controlled reference",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["verify_documents"],
    planRequirements:         [],
    featureRequirements:      ["verificationEnabled"],
    routeIds:                 ["app-verify","public-verify"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Verification service","Document hash registry"],
    dependencies:             [],
  },

  // ── MY ACTIONS (RECIPIENT INBOX) ──────────────────────────────────────────
  {
    id:                       capabilityId("my-actions"),
    label:                    "My Actions",
    description:              "Authenticated recipient inbox — documents assigned to the current user for action",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["app-inbox"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Participant service","Transaction service"],
    dependencies:             [],
  },

  // ── NOTIFICATIONS ─────────────────────────────────────────────────────────
  {
    id:                       capabilityId("notifications"),
    label:                    "Notifications",
    description:              "In-app notification center — document status, security, and workspace alerts",
    group:                    "Core",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      ["notificationsEnabled"],
    routeIds:                 ["app-notifications"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Notification service","Email delivery"],
    dependencies:             [],
  },

  // ── PROFILE & SETTINGS ────────────────────────────────────────────────────
  {
    id:                       capabilityId("profile-and-settings"),
    label:                    "Profile & Settings",
    description:              "Profile, preferences, security, notification preferences, branding, billing, usage, integrations, data and privacy",
    group:                    "Account",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["app-settings"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["User service","Billing service","Notification service"],
    dependencies:             [],
  },

  // ── WORKSPACE ADMINISTRATION ──────────────────────────────────────────────
  {
    id:                       capabilityId("workspace-administration"),
    label:                    "Workspace Administration",
    description:              "Members, teams, roles, invitations, and workspace settings",
    group:                    "Administration",
    maturity:                 "launch-core",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["manage_team"],
    planRequirements:         [],
    featureRequirements:      ["teamEnabled"],
    routeIds:                 ["app-workspace"],
    unavailableReason:        "Workspace administration requires the manage_team permission.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/settings/profile",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Workspace service","Member service","Role service","Invitation service"],
    dependencies:             [],
  },

  // ── SIGNATURE LIBRARY ─────────────────────────────────────────────────────
  {
    id:                       capabilityId("signature-library"),
    label:                    "Signature & Initials Library",
    description:              "Personal frontend signature and initials library",
    group:                    "Account",
    maturity:                 "launch-supporting",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["app-settings-signatures"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/settings/profile",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Signature storage service"],
    dependencies:             [],
  },

  // ── GLOBAL SEARCH ─────────────────────────────────────────────────────────
  {
    id:                       capabilityId("global-search"),
    label:                    "Global Search",
    description:              "Cross-platform search for documents, templates, contacts, settings, and help",
    group:                    "Navigation",
    maturity:                 "launch-supporting",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["app-search"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Search index service"],
    dependencies:             [],
  },

  // ── BASIC DOCUMENT ORGANIZATION ───────────────────────────────────────────
  {
    id:                       capabilityId("basic-document-organization"),
    label:                    "Document Organization",
    description:              "Folders, tags, starred documents, and recently viewed",
    group:                    "Documents",
    maturity:                 "launch-supporting",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     false,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-documents-folders","app-documents-tags"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Folder service","Tag service"],
    dependencies:             [capabilityId("documents")],
  },

  // ── BASIC REPORTS ─────────────────────────────────────────────────────────
  {
    id:                       capabilityId("basic-reports"),
    label:                    "Reports",
    description:              "Document operations, participant status, template usage, and workspace activity reports",
    group:                    "Insights",
    maturity:                 "launch-supporting",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        true,
    navigationVisibility:     true,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["view_reports"],
    planRequirements:         [],
    featureRequirements:      ["reportsEnabled"],
    routeIds:                 ["app-reports"],
    unavailableReason:        "Reports require the view_reports permission.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Reporting service","Analytics data store"],
    dependencies:             [],
  },

  // ── ADVANCED DOCUMENT ORGANIZATION ───────────────────────────────────────
  {
    id:                       capabilityId("advanced-document-organization"),
    label:                    "Advanced Document Organization",
    description:              "Deep nested folders, complex saved views, advanced bulk operations, and export previews",
    group:                    "Documents",
    maturity:                 "post-launch",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-documents-saved-views"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents/folders",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Folder service","Saved view service"],
    dependencies:             [capabilityId("basic-document-organization")],
  },

  // ── ADVANCED REPORTS ─────────────────────────────────────────────────────
  {
    id:                       capabilityId("advanced-reports"),
    label:                    "Advanced Reports",
    description:              "Complex analytics, productivity rankings, saved report views, and export previews",
    group:                    "Insights",
    maturity:                 "post-launch",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "service-required",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_reports"],
    planRequirements:         [],
    featureRequirements:      ["reportsEnabled"],
    routeIds:                 ["app-reports-saved"],
    unavailableReason:        "",
    previewNotice:            "",
    safeFallbackRoute:        "/app/reports",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Advanced analytics service"],
    dependencies:             [capabilityId("basic-reports")],
  },

  // ── WORKFLOW AUTOMATION ───────────────────────────────────────────────────
  {
    id:                       capabilityId("workflow-automation"),
    label:                    "Workflow Automation",
    description:              "Event-driven rules, reusable policies, simulations, conflict detection, and automation activity",
    group:                    "Advanced",
    maturity:                 "enterprise-preview",
    enabledByDefault:         false,
    frontendReady:            "complete-demonstration",
    backendReady:             "not-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_workflow_automation"],
    planRequirements:         [],
    featureRequirements:      ["automationEnabled"],
    routeIds:                 ["app-automation"],
    unavailableReason:        "Workflow Automation is an Enterprise Preview capability not included in the current product profile.",
    previewNotice:            "Active in Enterprise Preview — rules and policies operate in demonstration mode only. Backend automation engine not yet implemented.",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Automation engine","Rule evaluation service","Policy enforcement service","Conflict detection service","Event bus"],
    dependencies:             [],
  },

  // ── INTEGRATIONS ─────────────────────────────────────────────────────────
  {
    id:                       capabilityId("integrations"),
    label:                    "Integrations",
    description:              "Third-party service integrations",
    group:                    "Advanced",
    maturity:                 "post-launch",
    enabledByDefault:         true,
    frontendReady:            "complete-demonstration",
    backendReady:             "not-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["manage_integrations"],
    planRequirements:         [],
    featureRequirements:      ["integrationsEnabled"],
    routeIds:                 ["app-settings-integrations"],
    unavailableReason:        "",
    previewNotice:            "Integrations are in preview — no production connections are active.",
    safeFallbackRoute:        "/app/settings",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Integration service","OAuth gateway","Webhook delivery"],
    dependencies:             [],
  },

  // ── DEVELOPMENT SCENARIOS ─────────────────────────────────────────────────
  {
    id:                       capabilityId("development-scenarios"),
    label:                    "Development Scenarios",
    description:              "Fixture selectors, scenario controls, QA panels, and permission simulators",
    group:                    "Development",
    maturity:                 "development-only",
    enabledByDefault:         false,
    frontendReady:            "complete-demonstration",
    backendReady:             "not-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      ["developmentPlaceholdersEnabled"],
    routeIds:                 [],
    unavailableReason:        "Development tools are not available in the current profile.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/dashboard",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      [],
    dependencies:             [],
  },

  // ── FUTURE: eNOTARY ───────────────────────────────────────────────────────
  {
    id:                       capabilityId("future-enotary"),
    label:                    "eNotary",
    description:              "LAGDA eNotary — Coming Soon — Subject to Supreme Court Accreditation and applicable rules.",
    group:                    "Future",
    maturity:                 "future-product",
    enabledByDefault:         false,
    frontendReady:            "partial",
    backendReady:             "not-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 ["enotary"],
    unavailableReason:        "LAGDA eNotary is Coming Soon — Subject to Supreme Court Accreditation and applicable rules.",
    previewNotice:            "LAGDA eNotary is Coming Soon — Subject to Supreme Court Accreditation and applicable rules.",
    safeFallbackRoute:        "/enotary",
    indexable:                true,
    sitemapInclude:           true,
    backendDependencies:      ["eNotary platform (future)"],
    dependencies:             [],
  },

  // ── BULK SEND (C33) ──────────────────────────────────────────────────────
  // Reclassified from "deferred" to "enterprise-preview" when Command 33 was
  // implemented. `deferred` is evaluated before the profile allowlist in
  // capability-resolver.ts and returns unavailable in EVERY profile, which would
  // have made the whole route family unreachable. Enterprise Preview mirrors how
  // Workflow Automation (C32) is handled: fully built, disabled in the default
  // launch profile, usable with VITE_LAUNCH_PROFILE=enterprise-preview.
  {
    id:                       capabilityId("bulk-send"),
    label:                    "Bulk Send",
    description:              "Prepare one approved Template against many recipient rows, validate mappings, and create frontend Draft Projections",
    group:                    "Advanced",
    maturity:                 "enterprise-preview",
    enabledByDefault:         false,
    frontendReady:            "complete-demonstration",
    backendReady:             "contract-defined",
    publicLaunchReady:        false,
    // Gap Closure Command 5 — these flags now describe registered providers
    // rather than intent. Search, Command Palette and Dashboard contributions
    // exist and are gated on this capability.
    //
    // `navigationVisibility` stays false deliberately: Bulk Send is reached from
    // Documents and from a Template, and adding a top-level item would promote an
    // Enterprise Preview capability above launch features in the primary
    // navigation. It is not a permission decision — a user who can reach the
    // routes can still reach them by every other path.
    navigationVisibility:     false,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      true,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-bulk-send","app-bulk-send-new","app-bulk-send-batch","app-bulk-send-recipients","app-bulk-send-mapping","app-bulk-send-review","app-bulk-send-results","app-bulk-send-configurations","app-bulk-send-configuration"],
    unavailableReason:        "Bulk Send is an Enterprise Preview capability not included in the current product profile.",
    previewNotice:            "Active in Enterprise Preview — batches, mappings, validation, and Draft Projections operate in frontend demonstration only. No request is sent and no production transaction is created.",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Bulk operation service","Import processing","Validation pipeline","Queue and workers","Transaction creation","Email delivery"],
    dependencies:             [capabilityId("documents"), capabilityId("templates")],
  },

  // ── DOCUMENT COLLABORATION (C34) ─────────────────────────────────────────
  {
    id:                       capabilityId("document-collaboration"),
    label:                    "Document Collaboration",
    // Asynchronous internal review only. Real-time collaboration, presence, typing
    // indicators, and live cursors are explicitly out of scope for this capability.
    description:              "Internal review threads, comments, mentions, and resolution within documents",
    group:                    "Advanced",
    maturity:                 "enterprise-preview",
    enabledByDefault:         false,
    frontendReady:            "complete-demonstration",
    backendReady:             "contract-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         true,
    commandPaletteVisibility: true,
    dashboardVisibility:      false,
    permissionRequirements:   ["view_documents"],
    planRequirements:         [],
    featureRequirements:      ["documentsEnabled"],
    routeIds:                 ["app-document-collaboration","app-document-collaboration-thread","app-document-collaboration-new","app-document-review","app-collaboration-center","app-collaboration-assigned","app-collaboration-mentions","app-collaboration-blocking","app-collaboration-resolved"],
    unavailableReason:        "Document Collaboration is an Enterprise Preview capability not included in the current product profile.",
    previewNotice:            "Active in Enterprise Preview — threads, comments, mentions, and internal review operate in frontend demonstration only. Nothing is delivered, persisted, or recorded, and internal review is not participant approval.",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Collaboration service","Comment storage","Mention resolution","Notification delivery"],
    dependencies:             [capabilityId("documents")],
  },

  // ── DEFERRED ─────────────────────────────────────────────────────────────
  {
    id:                       capabilityId("document-versioning"),
    label:                    "Document Versioning",
    description:              "Version history, revision comparison, and redlining",
    group:                    "Deferred",
    maturity:                 "deferred",
    enabledByDefault:         false,
    frontendReady:            "not-started",
    backendReady:             "not-defined",
    publicLaunchReady:        false,
    navigationVisibility:     false,
    searchVisibility:         false,
    commandPaletteVisibility: false,
    dashboardVisibility:      false,
    permissionRequirements:   [],
    planRequirements:         [],
    featureRequirements:      [],
    routeIds:                 [],
    unavailableReason:        "Document versioning is deferred to a future release.",
    previewNotice:            "",
    safeFallbackRoute:        "/app/documents",
    indexable:                false,
    sitemapInclude:           false,
    backendDependencies:      ["Version control service","Diff engine"],
    dependencies:             [],
  },
];

// ── Index by ID ───────────────────────────────────────────────────────────────

const _index = new Map<string, ProductCapability>();
for (const cap of REGISTRY) {
  _index.set(cap.id, cap);
}

export function getCapability(id: ProductCapabilityId | string): ProductCapability | undefined {
  return _index.get(id);
}

export function getAllCapabilities(): ProductCapability[] {
  return REGISTRY;
}

export function getCapabilitiesByMaturity(maturity: import("../models/product-capability").ProductCapabilityMaturity): ProductCapability[] {
  return REGISTRY.filter(c => c.maturity === maturity);
}

export { REGISTRY as PRODUCT_CAPABILITY_REGISTRY };
